name = "udondon-mc"
author = "udondon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c88e86e2b9fe1a1b0973229f2fc519de2a77101c442dc59bc19c848af2651a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
